//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantDataAccess.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public int billId { get; set; }
        public Nullable<int> orderId { get; set; }
        public Nullable<System.DateTime> billDate { get; set; }
        public decimal billingAmount { get; set; }
        public bool isCardPayment { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
