//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantDataAccess.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int cartId { get; set; }
        public Nullable<int> menuItemId { get; set; }
        public Nullable<int> addedBy { get; set; }
        public int quantity { get; set; }
        public bool isOrdered { get; set; }
    
        public virtual User User { get; set; }
        public virtual MenuItem MenuItem { get; set; }
    }
}
