//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantDataAccess.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuItem
    {
        public MenuItem()
        {
            this.Carts = new HashSet<Cart>();
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int itemId { get; set; }
        public string itemName { get; set; }
        public string itemDescription { get; set; }
        public decimal price { get; set; }
        public Nullable<int> categoryID { get; set; }
        public int availableQty { get; set; }
        public bool itemStatusTitle { get; set; }
        public int createdBy { get; set; }
        public Nullable<int> updatedBy { get; set; }
        public Nullable<int> deletedBy { get; set; }
    
        public virtual ICollection<Cart> Carts { get; set; }
        public virtual MenuCategory MenuCategory { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
