//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantDataAccess.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderStatu
    {
        public OrderStatu()
        {
            this.OrderFlows = new HashSet<OrderFlow>();
            this.OrderFlows1 = new HashSet<OrderFlow>();
            this.OrderHistories = new HashSet<OrderHistory>();
        }
    
        public int orderStatusId { get; set; }
        public string orderStatusTitle { get; set; }
    
        public virtual ICollection<OrderFlow> OrderFlows { get; set; }
        public virtual ICollection<OrderFlow> OrderFlows1 { get; set; }
        public virtual ICollection<OrderHistory> OrderHistories { get; set; }
    }
}
