//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantDataAccess.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderFlow
    {
        public int orderFlowId { get; set; }
        public int currentStatus { get; set; }
        public Nullable<int> nextStatus { get; set; }
    
        public virtual OrderStatu OrderStatu { get; set; }
        public virtual OrderStatu OrderStatu1 { get; set; }
    }
}
