//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantDataAccess.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int orderId { get; set; }
        public int itemId { get; set; }
        public int itemQty { get; set; }
    
        public virtual MenuItem MenuItem { get; set; }
        public virtual Order Order { get; set; }
    }
}
