//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantDataAccess.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public Reservation()
        {
            this.Orders = new HashSet<Order>();
            this.Tables = new HashSet<Table>();
        }
    
        public int reservationId { get; set; }
        public System.DateTime reservationDate { get; set; }
        public Nullable<int> reservedBy { get; set; }
        public Nullable<int> numberOfPeople { get; set; }
        public System.TimeSpan startTime { get; set; }
        public Nullable<System.TimeSpan> endTime { get; set; }
    
        public virtual ICollection<Order> Orders { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Table> Tables { get; set; }
    }
}
