//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantDataAccess.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public Table()
        {
            this.Reservations = new HashSet<Reservation>();
        }
    
        public int tableID { get; set; }
        public int capacity { get; set; }
        public bool isTableAvailable { get; set; }
    
        public virtual ICollection<Reservation> Reservations { get; set; }
    }
}
